"""Build a deploy-ready tarball for the Linux/Hetzner server.

Output: build/runway-server.tar.gz

The bundle bakes RUNWAY_UI_MODE=web into the code (via app/_build_mode.py),
so the server side needs zero env config. Deploy flow:

    scp build/runway-server.tar.gz user@host:~
    tar xzf runway-server.tar.gz
    cd runway-server
    ./run.sh                       # one-shot: makes venv, installs deps, runs
    # or: install runway.service into systemd for autostart

Usage:
    python scripts/build_server.py
"""
from __future__ import annotations

import shutil
import sys
import tarfile
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
BUILD_ROOT = PROJECT_ROOT / "build" / "server"
BUNDLE_NAME = "runway-server"
TARBALL = PROJECT_ROOT / "build" / f"{BUNDLE_NAME}.tar.gz"


# What the tarball contains. Everything else is dev-only.
INCLUDE_FILES = [
    "requirements_server.txt",
]
INCLUDE_DIRS = [
    "app",
]

# What to strip while copying the `app/` tree.
_PYCACHE = {"__pycache__"}


def _copy_app_tree(src: Path, dst: Path) -> None:
    """Copy src → dst, skipping __pycache__ and .pyc files."""
    def ignore(_dir: str, names: list[str]) -> list[str]:
        return [n for n in names if n in _PYCACHE or n.endswith(".pyc")]
    shutil.copytree(src, dst, ignore=ignore)


def _write_build_mode(staging: Path) -> None:
    """Drop app/_build_mode.py so paths.is_web_mode() resolves to True
    without any env var on the server."""
    path = staging / "app" / "_build_mode.py"
    path.write_text(
        '"""Generated by scripts/build_server.py — do not edit by hand."""\n'
        'MODE = "web"\n',
        encoding="utf-8",
    )


def _write_run_sh(staging: Path) -> None:
    path = staging / "run.sh"
    path.write_text(
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        'cd "$(dirname "$(readlink -f "$0")")"\n'
        "\n"
        "if [ ! -d .venv ]; then\n"
        '  echo "[run.sh] creating venv + installing deps (one-time)…"\n'
        "  python3 -m venv .venv\n"
        "  .venv/bin/pip install --upgrade pip\n"
        "  .venv/bin/pip install -r requirements_server.txt\n"
        "fi\n"
        "\n"
        'exec .venv/bin/python -m app.ui.app\n',
        encoding="utf-8",
    )
    path.chmod(0o755)


def _write_systemd_unit(staging: Path) -> None:
    """Template — user edits paths/User before installing."""
    path = staging / "runway.service"
    path.write_text(
        "# Install:\n"
        "#   sudo cp runway.service /etc/systemd/system/\n"
        "#   sudo systemctl daemon-reload && sudo systemctl enable --now runway\n"
        "#\n"
        "# Edit WorkingDirectory/User/ExecStart to match where you extracted the bundle.\n"
        "[Unit]\n"
        "Description=Runway Automation (web)\n"
        "After=network-online.target\n"
        "Wants=network-online.target\n"
        "\n"
        "[Service]\n"
        "Type=simple\n"
        "WorkingDirectory=/opt/runway-server\n"
        "ExecStart=/opt/runway-server/run.sh\n"
        "Restart=on-failure\n"
        "RestartSec=5\n"
        "# User=runway\n"
        "# Group=runway\n"
        "\n"
        "[Install]\n"
        "WantedBy=multi-user.target\n",
        encoding="utf-8",
    )


def _write_readme(staging: Path) -> None:
    path = staging / "README.md"
    path.write_text(
        "# Runway Automation — server bundle\n"
        "\n"
        "Auto-generated by `scripts/build_server.py`. Web mode is baked in via\n"
        "`app/_build_mode.py`; no env vars required.\n"
        "\n"
        "## Quick start\n"
        "\n"
        "```bash\n"
        "tar xzf runway-server.tar.gz\n"
        "cd runway-server\n"
        "./run.sh                              # creates venv on first run\n"
        "```\n"
        "\n"
        "App listens on `0.0.0.0:8551`. Open the Hetzner firewall for that port\n"
        "and visit `http://<host>:8551/`.\n"
        "\n"
        "## systemd (recommended)\n"
        "\n"
        "```bash\n"
        "sudo mv runway-server /opt/\n"
        "sudo cp /opt/runway-server/runway.service /etc/systemd/system/\n"
        "sudo systemctl daemon-reload && sudo systemctl enable --now runway\n"
        "sudo journalctl -u runway -f                  # tail logs\n"
        "```\n"
        "\n"
        "## Downloads\n"
        "\n"
        "Finished mp4s land in `downloads/` and are exposed at `/downloads/<file>.mp4`\n"
        "with `Content-Disposition: attachment` (browser triggers a Save dialog).\n"
        "The in-app folder icon navigates to the `/downloads` listing page.\n",
        encoding="utf-8",
    )


def build() -> int:
    print(f"[build] cleaning {BUILD_ROOT}…")
    if BUILD_ROOT.exists():
        shutil.rmtree(BUILD_ROOT)
    staging = BUILD_ROOT / BUNDLE_NAME
    staging.mkdir(parents=True)

    print("[build] copying source…")
    for name in INCLUDE_DIRS:
        src = PROJECT_ROOT / name
        if not src.is_dir():
            print(f"  ! missing dir: {src}", file=sys.stderr)
            return 1
        _copy_app_tree(src, staging / name)

    for name in INCLUDE_FILES:
        src = PROJECT_ROOT / name
        if not src.is_file():
            print(f"  ! missing file: {src}", file=sys.stderr)
            return 1
        shutil.copy2(src, staging / name)

    print("[build] baking MODE=web…")
    _write_build_mode(staging)

    print("[build] writing run.sh, runway.service, README.md…")
    _write_run_sh(staging)
    _write_systemd_unit(staging)
    _write_readme(staging)

    print(f"[build] packing {TARBALL.name}…")
    TARBALL.parent.mkdir(parents=True, exist_ok=True)
    if TARBALL.exists():
        TARBALL.unlink()
    with tarfile.open(TARBALL, "w:gz") as tf:
        tf.add(staging, arcname=BUNDLE_NAME)

    size_mb = TARBALL.stat().st_size / 1024 / 1024
    print(f"[build] done: {TARBALL}  ({size_mb:.2f} MB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(build())
